#ifndef __WSH_SHELL_VERSION_H
#define __WSH_SHELL_VERSION_H

#define WSH_SHELL_VERSION_MAJOR 2
#define WSH_SHELL_VERSION_MINOR 3

#define _WSH_SHELL_STR_HELPER(x) #x
#define _WSH_SHELL_STR(x)        _WSH_SHELL_STR_HELPER(x)
#define WSH_SHELL_VERSION_STR \
    _WSH_SHELL_STR(WSH_SHELL_VERSION_MAJOR) "." _WSH_SHELL_STR(WSH_SHELL_VERSION_MINOR)

#endif /* __WSH_SHELL_VERSION_H */
